services:
  ta:
    image: oidfed/lighthouse:main
    container_name: oidf-ta
    restart: unless-stopped
    ports:
      - "7672:7672"
    volumes:
      - ./ta/config.yaml:/config.yaml:ro
      - ./ta/data:/data

  ia:
    image: oidfed/lighthouse:main
    container_name: oidf-ia
    restart: unless-stopped
    ports:
      - "7673:7673"
    volumes:
      - ./ia/config.yaml:/config.yaml:ro
      - ./ia/data:/data

  rp:
    image: oidfed/whoami-rp
    container_name: oidf-rp
    hostname: rp
    restart: unless-stopped
    ports:
      - "7680:7680"
    volumes:
      - ./rp/config.yaml:/config.yaml:ro
      - rp-keys:/keys

volumes:
  rp-keys:
