services:
  lighthouse:
    image: oidfed/lighthouse:main
    restart: unless-stopped
    ports:
      - "7672:7672"
    volumes:
      - ./lighthouse/config.yaml:/config.yaml:ro
      - ./lighthouse/data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  leaf:
    image: oidfed/lighthouse:main
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./leaf/leaf-config.yaml:/config.yaml:ro
      - ./leaf/data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
