server:
  port: 8787

signing:
  alg: ES256
  key_dir: "/data/signing"

federation_data:
  entity_id: "http://localhost:8787"
  authority_hints:
    - "http://localhost:7672"
  federation_entity_metadata:
    display_name: "Leaf Entity"
    organization_name: "Minha Org Dev"

storage:
  backend: badger
  data_dir: "/data/storage"

endpoints:
  fetch: { path: "/fetch" }
